#!/usr/bin/python

counter = 100          # An integer assignment
miles   = 1000.0       # A floating point
name    = "John Cena"       # A string
name2  ="Abdul Rahiman"       # A string

print counter
print miles
print name
print name2
